os: Visual Studio 2017
version: 1.0.{build}

environment:
  CLI_VERSION: 2.0.0-preview1-005977
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: .\Build.ps1

artifacts:
  - path: artifacts

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
